---
- name: 'MAIN | AWS Resource Inventory Playbook'
  hosts: 'localhost'
  gather_facts: false

  # Environment Variable
  vars:
    - ansible_python_interpreter: '/bin/python2'

  # Pre Requisite Task
#  pre_tasks:
#    - include_role:
#        name: 'aws-inventory'
#        tasks_from: 'check'

  # AWS inventory roles
  roles:
    - { role: 'aws-inventory', when: resource_type is defined }
