---
- name: 'MAIN | AWS Resource Inventory Playbook'
  hosts: localhost
  gather_facts: true

  # Environment Variable
  vars:
    - ansible_python_interpreter: '/bin/python2'

  # AWS inventory roles
  roles:
    - { role: "{{ resource_type[0] | default('') }}", tags: [ all, "{{ resource_type[0] | default('') }}" ], when: awx is defined }
    - { role: "{{ resource_type[1] | default('') }}", tags: [ all, "{{ resource_type[1] | default('') }}" ], when: awx is defined }
    - { role: "{{ resource_type[2] | default('') }}", tags: [ all, "{{ resource_type[2] | default('') }}" ], when: awx is defined }
    - { role: "{{ resource_type[3] | default('') }}", tags: [ all, "{{ resource_type[3] | default('') }}" ], when: awx is defined }
    - { role: "{{ resource_type[4] | default('') }}", tags: [ all, "{{ resource_type[4] | default('') }}" ], when: awx is defined }
    - { role: "{{ resource_type[5] | default('') }}", tags: [ all, "{{ resource_type[5] | default('') }}" ], when: awx is defined }

  tasks:
    - import_role:
        name: 'convert'
        tasks_from: 'main'
      tags: [ 'all', 'convert' ]
      when: awx is defined

  # - import_tasks: slack.yml
  #   when: task_type == 'all' or  task_type == 'part'