---
- name: 'MAIN | AWS Resource Inventory Playbook'
  hosts: 'localhost'
  gather_facts: true

  vars_files:
    - './secret.yml'

  # Input parameter value
  vars_prompt:
    - name: "parameter_value"
      prompt: |
        !!! Please select an AWS resource !!!
          - [ all ]
          - [ vpc ]
          - [ ec2 ]
          - [ s3  ]
          - [ sg  ]
          - [ rds ]
      private: false

  # AWS inventory roles
  roles:
    - { role: 'aws-inventory', when: parameter_value is defined }
