---
- block:
    - name: 'CloudFront | Gather information about Distributions in AWS'
      cloudfront_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        summary: true
      register: 'cf_distribution_result'
      no_log: true

    - name: 'CloudFront | Create variable about Distributions in AWS'
      set_fact:
        aws_cf_id: "{{ cf_distribution_result | json_query('summary.distributions[*].Id') }}"
        aws_cf_domain: "{{ cf_distribution_result | json_query('distributions.DomainName') }}"

    - name: 'CloudFront | Create Jinja template about Route in AWS'
      template:
        src: "{{ role_path }}/templates/cf-template.j2"
        dest: "{{ role_path }}/files/cf-template.csv"
        mode: '0644'
        force: true

    - name: 'Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'

  rescue:
    - name: 'Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
