---
- block:
    - name: 'ROUTE53 | Gather information about Hosted Zone in AWS'
      route53_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        query: 'hosted_zone'
      register: 'route53_zone_result'
      no_log: false

    - name: 'ROUTE53 | Create variable about Hosted Zone in AWS'
      set_fact:
        aws_route53_type: "{{ route53_zone_result | json_query('HostedZones[*].Config.PrivateZone') }}"
        aws_route53_domain: "{{ route53_zone_result | json_query('HostedZones[*].Name') }}"
        aws_route53_comment: "{{ route53_zone_result | json_query('HostedZones[*].Config.Comment') }}"
        aws_route53_record_count: "{{ route53_zone_result | json_query('HostedZones[*].ResourceRecordSetCount')  }}"

    - name: 'ROUTE53 | Create Jinja template about Route in AWS'
      template:
        src: "{{ role_path }}/templates/{{ parameter_value }}-template.j2"
        dest: "{{ role_path }}/files/{{ parameter_value }}-report.csv"
        mode: '0644'
        force: true

    - name: 'Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'

  rescue:
    - name: 'Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
