---
- block:
    - name: 'S3 | Gather information about s3 bucket in AWS'
      aws_s3_bucket_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: 's3_bucket_result'
      no_log: false

    - name: 'S3 | Create variable about s3 bucket in AWS'
      set_fact:
        aws_s3_bucket: "{{ s3_bucket_result | json_query('buckets[*].name') }}"

    - name: 'S3 | Create Jinja template about s3 bucket in AWS'
      template:
        src: "{{ role_path }}/templates/{{ resource_type }}-template.j2"
        dest: "{{ role_path }}/files/{{ resource_type }}-report.csv"
        mode: '0644'
        force: true

    - name: 'Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'

  rescue:
    - name: 'Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
