---
- block:
    - name: 'VPC | Gather information about VPC in AWS'
      ec2_vpc_net_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: 'vpc_net_result'

    - name: 'VPC | Create variable about VPC in AWS'
      set_fact:
#        aws_vpc_name: "{{ vpc_net_result | json_query('vpcs[*].tags.Name')   else '' }}"
        aws_vpc_name: "{{ vpc_net_result | json_query('vpcs[*].tags') | regex_replace('(Name)(.*),, '\\1') }}"
        aws_vpc_id: "{{ vpc_net_result | json_query('vpcs[*].vpc_id') }}"
        aws_vpc_cidr: "{{ vpc_net_result | json_query('vpcs[*].cidr_block') }}"

    - name: 'VPC | Create Jinja template about VPC in AWS'
      template:
        src: "{{ role_path }}/templates/vpc-template.j2"
        dest: "{{ role_path }}/files/vpc-template.csv"
        mode: '0644'
        force: true

    - name: 'Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'

  rescue:
    - name: 'Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
