---
- block:
    - name: 'SG | Gather information about SecurityGroup in AWS'
      ec2_group_facts:
        region: "{{ AWS_REGION }}"
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      register: 'sg_bucket_result'
      no_log: false
      delegate_to: localhost

    - name: 'SG | Create variable about SecurityGroup in AWS'
      set_fact:
        aws_sg_name: "{{ sg_bucket_result | json_query('security_groups[*].tags.Name') }}"
        aws_sg_id: "{{ sg_bucket_result | json_query('security_groups[*].group_id') }}"
        
        # aws_sg_potocol: "{{ sg_bucket_result | json_query('buckets[*].name') }}"
        # aws_sg_port: "{{ sg_bucket_result | json_query('buckets[*].name') }}"
        # aws_sg_source: "{{ sg_bucket_result | json_query('buckets[*].name') }}"
        aws_sg_description: "{{ sg_bucket_result | json_query('security_groups[*].description') }}"



    # - name: 'SG | Create Jinja template about SecurityGroup in AWS'
    #   template:
    #     src: "{{ role_path }}/templates/SG-template.j2"
    #     dest: "/tmp/SG-report.csv"
    #     mode: '0644'
    #     force: true
    #   delegate_to: localhost

    - name: 'SG | Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'
      delegate_to: localhost

  rescue:
    - name: 'SG | Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
      delegate_to: localhost
