---
- block:
    - name: 'CF | Gather information about Distributions in AWS'
      cloudfront_info:
        region: "{{ AWS_REGION }}"
        aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        summary: false
      register: 'cf_distribution_result'
      no_log: false
      delegate_to: localhost

    - name: 'CF | Create variable about Distributions in AWS'
      set_fact:
        aws_cf_id: "{{ cf_distribution_result | json_query('cloudfront.summary.distributions[*].Id') }}"
        aws_cf_status: "{{ cf_distribution_result | json_query('cloudfront.summary.distributions[*].Status') }}"
        aws_cf_domain: "{{ cf_distribution_result | json_query('cloudfront.summary.distributions[*].DomainName') }}"
      delegate_to: localhost

    - name: 'CF | Create Jinja template about Route in AWS'
      template:
        src: "{{ role_path }}/templates/cf-template.j2"
        dest: "{{ role_path }}/../../roles/convert/files/cf-report.csv"
        mode: '0644'
        force: true
      delegate_to: localhost

    - name: 'CF | Show success message'
      debug:
        msg:
          - '================'
          - '= TASK SUCCESS ='
          - '================'
      delegate_to: localhost

  rescue:
    - name: 'CF | Show failure message'
      debug:
        msg:
          - '================'
          - '= TASK FAILURE ='
          - '================'
      delegate_to: localhost